{"name": "test_a", "status": "skipped", "statusDetails": {"message": "XFAIL deliberate fail\n\nAssertionError: assert False", "trace": "@pytest.mark.dependency(name=\"a\")\n    @pytest.mark.xfail(reason=\"deliberate fail\")\n    def test_a():\n>       assert False\nE       assert False\n\ntest_depend.py:25: AssertionError"}, "start": 1678268172401, "stop": 1678268172409, "uuid": "82ce8b02-d6b0-463b-8e69-0c2a99312848", "historyId": "d59676383a9fcf405d69d55f4062a2fc", "testCaseId": "7ecde39b726729de2aad41fd9efbf809", "fullName": "test_depend#test_a", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='deliberate fail')"}, {"name": "tag", "value": "dependency(name='a')"}, {"name": "suite", "value": "test_depend"}, {"name": "host", "value": "BAN-LAP-VREDDY"}, {"name": "thread", "value": "7936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_depend"}]}